title: Israel Amogo Data Analytics Porfolio
logo: MyPix.png
description: A Data Analytics with 2 Years Experience analysing Data with Microsoft Excel, Power BI, SQL and SQL Server Integration Services(SSIS)
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
