title: Israel Amogo Data Analytics Porfolio
logo: download.jpg
description: A Data Analytics with 2 Years Experienc analysing Data with Excel, Power BI and SQL
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
